
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "QA_RULES_P0007_V"
  AS 
select QARU_ID
     , QARU_RULE_NUMBER
     , QARU_CLIENT_NAME
     , QARU_NAME
     , QARU_CATEGORY
     , QARU_OBJECT_TYPES
     , QARU_ERROR_MESSAGE
     , QARU_COMMENT
     , QARU_EXCLUDE_OBJECTS
     , QARU_ERROR_LEVEL
     , QARU_IS_ACTIVE
     , QARU_SQL
     , QARU_LAYER
from QA_RULES
;
/
