
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "QA_RULES_P0006_V"
  AS 
select QARU_ID
     , QARU_RULE_NUMBER
     , QARU_CLIENT_NAME
     , QARU_NAME
     , QARU_CATEGORY
     , QARU_ERROR_MESSAGE
     , QARU_COMMENT
     , QARU_ERROR_LEVEL
     , QARU_IS_ACTIVE
     , QARU_LAYER
     , QARU_CREATED_ON
     , QARU_CREATED_BY
     , QARU_UPDATED_ON
     , QARU_UPDATED_BY
from QA_RULES
;
/
