ALTER TABLE UTPLSQL_TEST_SUITE MODIFY (SUITE_ID NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_SUITE MODIFY (SUITE_CREATE_USER NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_SUITE MODIFY (SUITE_CREATE_DATE NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_SUITE MODIFY (SUITE_CHANGE_USER NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_SUITE MODIFY (SUITE_CHANGE_DATE NOT NULL ENABLE);