ALTER TABLE UTPLSQL_TEST_CASE MODIFY (CASE_ID NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_CASE MODIFY (CASE_CREATE_DATE NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_CASE MODIFY (CASE_CREATE_USER NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_CASE MODIFY (CASE_CHANGE_DATE NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_CASE MODIFY (CASE_CHANGE_USER NOT NULL ENABLE);