ALTER TABLE UTPLSQL_TEST_RUN MODIFY (RUN_ID NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_RUN MODIFY (RUN_CREATE_USER NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_RUN MODIFY (RUN_CREATE_DATE NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_RUN MODIFY (RUN_CHANGE_USER NOT NULL ENABLE);


ALTER TABLE UTPLSQL_TEST_RUN MODIFY (RUN_CHANGE_DATE NOT NULL ENABLE);