CREATE TABLE UTPLSQL_TEST_SUITE
   (	SUITE_ID NUMBER NOT NULL,
	SUITE_RUN_ID NUMBER,
	SUITE_PACKAGE_PATH VARCHAR2(100 CHAR),
	SUITE_TESTSUITE_NAME VARCHAR2(255 CHAR),
	SUITE_TESTSUITE_ID NUMBER,
	SUITE_TOTAL_TESTS NUMBER,
	SUITE_DISABLED_TESTS NUMBER,
	SUITE_ERRORED_TESTS NUMBER,
	SUITE_FAILED_TESTS NUMBER,
	SUITE_DURATION_SEC VARCHAR2(20 CHAR),
	SUITE_SYSTEM_OUT VARCHAR2(4000 CHAR),
	SUITE_SYSTEM_ERR VARCHAR2(4000 CHAR),
	SUITE_TSU_ID NUMBER,
	SUITE_SCHEMA VARCHAR2(50 CHAR),
	SUITE_CREATE_USER VARCHAR2(2550 CHAR) NOT NULL,
	SUITE_CREATE_DATE DATE NOT NULL,
	SUITE_CHANGE_USER VARCHAR2(255 CHAR) NOT NULL,
	SUITE_CHANGE_DATE DATE NOT NULL
   ) ;

COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_ID IS 'Primary Key';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_RUN_ID IS 'Foreign Key on utplsql_test_run';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_PACKAGE_PATH IS 'Package name of the test suite';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_TESTSUITE_NAME IS 'Name of test suite/ package name';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_TESTSUITE_ID IS 'ID of the testsuite';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_TOTAL_TESTS IS 'Number of total tests in this test suite';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_DISABLED_TESTS IS 'Number of disabled tests in this test suite';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_ERRORED_TESTS IS 'Number of errored tests in this test suite';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_FAILED_TESTS IS 'Number of failed tests in this test run';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_DURATION_SEC IS 'Duration in Seconds this test suite runs';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_SYSTEM_OUT IS 'System output of this test suite';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_SYSTEM_ERR IS 'Error output of this test suite';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_TSU_ID IS 'tsu Id';
   COMMENT ON COLUMN UTPLSQL_TEST_SUITE.SUITE_SCHEMA IS 'Schema this test suite belongs to';
   COMMENT ON TABLE UTPLSQL_TEST_SUITE  IS 'Table for test suite results';


ALTER TABLE UTPLSQL_TEST_SUITE
  ADD CONSTRAINT SUITE_PK PRIMARY KEY (SUITE_ID);

ALTER TABLE UTPLSQL_TEST_SUITE
  ADD CONSTRAINT SUITE_RUN_FK FOREIGN KEY (SUITE_RUN_ID) REFERENCES UTPLSQL_TEST_RUN (RUN_ID);