CREATE TABLE UTPLSQL_TEST_CASE
   (	CASE_ID NUMBER NOT NULL,
	CASE_SUITE_ID NUMBER,
	CASE_TESTCASE_PATH VARCHAR2(255 CHAR),
	CASE_TESTCASE_NAME VARCHAR2(255 CHAR),
	CASE_TEST_STATUS VARCHAR2(20 CHAR),
	CASE_ASSERTIONS NUMBER,
	CASE_DURATION_SEC VARCHAR2(20 CHAR),
	CASE_EXECUTED_ON DATE,
	CASE_ERROR_STATEMENT VARCHAR2(4000 CHAR),
	CASE_FAILURE_STATEMENT VARCHAR2(4000 CHAR),
	CASE_SYSTEM_OUT VARCHAR2(4000 CHAR),
	CASE_SYSTEM_ERR VARCHAR2(4000 CHAR),
	CASE_SCHEMA VARCHAR2(50 CHAR),
	CASE_CREATE_DATE DATE NOT NULL,
	CASE_CREATE_USER VARCHAR2(255 CHAR) NOT NULL,
	CASE_CHANGE_DATE DATE NOT NULL,
	CASE_CHANGE_USER VARCHAR2(255 CHAR) NOT NULL
   ) ;

COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_ID IS 'Primary Key';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_SUITE_ID IS 'Foreign Key on utplsql_test_suite';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_TESTCASE_PATH IS 'Path/Package of the testcase';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_TESTCASE_NAME IS 'Name of the testcase';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_TEST_STATUS IS 'status of this testrun';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_ASSERTIONS IS 'assertions of testcase';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_DURATION_SEC IS 'duration of testcase run in seconds';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_EXECUTED_ON IS 'date of testcase run';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_ERROR_STATEMENT IS 'Comments when testcase has an error';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_SYSTEM_OUT IS 'System output of testcase run';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_SYSTEM_ERR IS 'Error output of testcase run';
   COMMENT ON COLUMN UTPLSQL_TEST_CASE.CASE_SCHEMA IS 'Schema for which the testcase was run';
   COMMENT ON TABLE UTPLSQL_TEST_CASE  IS 'Table for specific testcases and their results';


ALTER TABLE UTPLSQL_TEST_CASE
  ADD CONSTRAINT CASE_PK PRIMARY KEY (CASE_ID);

ALTER TABLE UTPLSQL_TEST_CASE
  ADD CONSTRAINT CASE_SUITE_FK FOREIGN KEY (CASE_SUITE_ID) REFERENCES UTPLSQL_TEST_SUITE (SUITE_ID);
