CREATE TABLE UTPLSQL_TEST_RUN
   (	RUN_ID NUMBER NOT NULL,
	RUN_START_DATE DATE,
	RUN_END_DATE DATE,
	RUN_TEST_RESULT_XML CLOB,
	RUN_TOTAL_TESTS NUMBER,
	RUN_DISABLED_TESTS NUMBER,
	RUN_ERRORED_TESTS NUMBER,
	RUN_FAILED_TESTS NUMBER,
	RUN_DURATION_SEC VARCHAR2(20 CHAR),
	RUN_CREATE_USER VARCHAR2(255 CHAR) NOT NULL,
	RUN_CREATE_DATE DATE NOT NULL,
	RUN_CHANGE_USER VARCHAR2(255 CHAR) NOT NULL,
	RUN_CHANGE_DATE DATE NOT NULL
   ) ;

COMMENT ON COLUMN UTPLSQL_TEST_RUN.RUN_ID IS 'Primary Key';
   COMMENT ON COLUMN UTPLSQL_TEST_RUN.RUN_START_DATE IS 'Beginning of test run';
   COMMENT ON COLUMN UTPLSQL_TEST_RUN.RUN_END_DATE IS 'End of test run';
   COMMENT ON COLUMN UTPLSQL_TEST_RUN.RUN_TEST_RESULT_XML IS 'Test results in xml';
   COMMENT ON COLUMN UTPLSQL_TEST_RUN.RUN_TOTAL_TESTS IS 'Number of total tests in this test run';
   COMMENT ON COLUMN UTPLSQL_TEST_RUN.RUN_DISABLED_TESTS IS 'Number of disabled tests in this test run';
   COMMENT ON COLUMN UTPLSQL_TEST_RUN.RUN_ERRORED_TESTS IS 'Number of errored tests in this test run';
   COMMENT ON COLUMN UTPLSQL_TEST_RUN.RUN_FAILED_TESTS IS 'Number of failed tests in this test run';
   COMMENT ON TABLE UTPLSQL_TEST_RUN  IS 'Table for testruns and their results';


ALTER TABLE UTPLSQL_TEST_RUN
  ADD CONSTRAINT RUN_PK PRIMARY KEY (RUN_ID);