PROMPT SQL file for installing the utPLSQL objects on a database. Called from install_objects.sql.
@src/ddl/tab/utplsql_calendar.sql
@src/ddl/tab/utplsql_test_case.sql
@src/ddl/tab/utplsql_test_run.sql
@src/ddl/tab/utplsql_test_suite.sql
@src/ddl/seq/cldr_seq.sql
@src/ddl/seq/case_seq.sql
@src/ddl/seq/run_seq.sql
@src/ddl/seq/suite_seq.sql
@src/ddl/cons/utplsql_test_case.sql
@src/ddl/cons/utplsql_test_run.sql
@src/ddl/cons/utplsql_test_suite.sql
@src/ddl/ind/utplsql_test_case.sql
@src/ddl/ind/utplsql_test_run.sql
@src/ddl/ind/utplsql_test_suite.sql
@src/ddl/fk/utplsql_test_case.sql
@src/ddl/fk/utplsql_test_suite.sql
@src/plsql/typ/t_varchar2_tab.sql
@src/plsql/pkg/prepare_test_results_pkg.sql
@src/plsql/trg/cldr_iu_trg.sql
@src/plsql/trg/case_iu_trg.sql
@src/plsql/trg/run_iu_trg.sql
@src/plsql/trg/suite_ui_trg.sql